#!/usr/bin/env python3
"""Regenerate js/dictionary.js from source word lists.

Inputs (expected in ../data/):
  en_50k.txt      word-frequency list (FrequencyWords en 50k)
  words_alpha.txt broad English word list (dwyl/english-words)
  enable1.txt     ENABLE word-game lexicon (dolph/dictionary)

Output: ../js/dictionary.js with COMMON (frequent words), TARGETS
(frequent ∩ ENABLE, used for wheels/grids), VALID (accepted submissions).
Run from the project root: python3 tools/build_dictionary.py
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def ok(w): return w.isalpha() and w.islower() and 3 <= len(w) <= 8

def load(path):
    with open(os.path.join(ROOT, 'data', path)) as f:
        return [line.split()[0].strip() for line in f if line.split()]

BLOCK = set("""shit fuck cunt slut whore bitch nigger negro fag faggot dyke kike spic
chink wop gook coon piss cock dick twat wank arse hoe tits boob porn rape nazi anal sex cum pussy
penis vagina dildo orgy erotic fetish bastard damn hell bloody crap fart poop turd dickhead asshole
motherfucker bullshit dumbass jackass prick schmuck puta merde scheisse verga con carajo mierda
putain salope bordel chier foutre encule zob bite couilles nichons gland branler""".split())

freq = [w for w in load('en_50k.txt') if ok(w)]
alpha = {w for w in load('words_alpha.txt') if ok(w)}
enable = {w for w in load('enable1.txt') if ok(w)}

common, seen = [], set()
for w in freq:
    if w in alpha and w not in BLOCK and w not in seen:
        seen.add(w)
        common.append(w)
valid = sorted(set(common))
targets = [w for w in common if w in enable]

with open(os.path.join(ROOT, 'js', 'dictionary.js'), 'w') as f:
    f.write('// Word Grove dictionary — GENERATED by tools/build_dictionary.py. Do not edit.\n')
    f.write('// TARGETS: frequent ∩ ENABLE (wheels/grid words). VALID: accepted submissions.\n')
    f.write('export const COMMON_TEXT =\n"%s";\n' % ' '.join(common))
    f.write('export const TARGET_TEXT =\n"%s";\n' % ' '.join(targets))
    f.write('export const VALID_TEXT =\n"%s";\n' % ' '.join(valid))
    f.write('''
export const COMMON = COMMON_TEXT.split(" ");
export const TARGETS = TARGET_TEXT.split(" ");
export const VALID = new Set(VALID_TEXT.split(" "));
export const COMMON_SET = new Set(COMMON);
export const TARGET_SET = new Set(TARGETS);
export function isValidWord(w) { return VALID.has(w); }
export function isCommonWord(w) { return COMMON_SET.has(w); }
''')
print(f'common={len(common)} targets={len(targets)} valid={len(valid)}')
